import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Mic,
  MicOff,
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  Pill,
  Car,
  ShoppingBag,
  HeartHandshake,
  FileText
} from 'lucide-react';
import { AIService } from '@/services/ai/ai.service';
import { useRequestsQuery } from '@/hooks/useRequestsQuery';
import { useAuth } from '@/contexts/AuthContext';
import type { RequestCategory, RequestUrgency } from '@/types/database.types';

export const NewRequestWizard: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { createRequest, isCreating } = useRequestsQuery();

  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [naturalText, setNaturalText] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [isClassifying, setIsClassifying] = useState(false);

  // Structured fields generated by AI or edited by user
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<RequestCategory>('medicine_pickup');
  const [urgency, setUrgency] = useState<RequestUrgency>('today');
  const [description, setDescription] = useState('');
  const [address, setAddress] = useState('Petta Junction, Kanjirappally, Kerala');
  const [isEmergencyDetected, setIsEmergencyDetected] = useState(false);

  const handleVoiceToggle = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) return;

    if (isListening) {
      setIsListening(false);
      return;
    }

    try {
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.lang = 'en-IN';
      recognition.onstart = () => setIsListening(true);
      recognition.onend = () => setIsListening(false);
      recognition.onerror = () => setIsListening(false);
      recognition.onresult = (e: any) => {
        const text = e.results?.[0]?.[0]?.transcript;
        if (text) {
          setNaturalText((prev) => (prev ? `${prev} ${text}` : text));
        }
      };
      recognition.start();
    } catch {
      setIsListening(false);
    }
  };

  const handleProcessWithAI = async () => {
    if (!naturalText.trim()) return;
    setIsClassifying(true);

    try {
      const classification = await AIService.classifyRequest(naturalText);

      if (classification.is_emergency) {
        setIsEmergencyDetected(true);
      }

      setTitle(
        classification.intent === 'pharmacy_pickup'
          ? 'Pharmacy & Medicine Delivery'
          : classification.intent === 'medical_transport'
          ? 'Medical Transportation Assistance'
          : classification.intent === 'grocery_pickup'
          ? 'Essential Groceries Assistance'
          : 'Community Help Request'
      );
      setCategory(classification.category as RequestCategory);
      setUrgency(classification.urgency);
      setDescription(naturalText);
      setStep(2);
    } catch (err) {
      console.error(err);
      setTitle('Community Assistance');
      setDescription(naturalText);
      setStep(2);
    } finally {
      setIsClassifying(false);
    }
  };

  const handleFinalSubmit = async () => {
    if (!user) return;

    await createRequest({
      requester_id: user.id,
      title,
      description,
      category,
      urgency,
      address,
      latitude: 9.5550,
      longitude: 76.7885,
      voice_transcript: naturalText,
      status: 'submitted'
    });

    navigate('/home');
  };

  return (
    <div className="pb-36 px-4 pt-6 max-w-lg mx-auto space-y-6 text-stone-900 dark:text-stone-100 transition-colors">
      {/* Top Header */}
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={() => (step > 1 ? setStep((step - 1) as any) : navigate('/home'))}
          className="p-2.5 rounded-2xl bg-stone-100 dark:bg-stone-800 hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-700 dark:text-stone-300 transition-colors"
          aria-label="Back"
        >
          <ArrowLeft className="w-6 h-6" />
        </button>
        <div>
          <h1 className="text-2xl font-black text-[#121E1C] dark:text-white tracking-tight">Request Assistance</h1>
          <p className="text-xs text-stone-500 dark:text-stone-400 font-medium">Step {step} of 3 · Voice & AI Powered</p>
        </div>
      </div>

      {/* Progress Dots */}
      <div className="flex items-center justify-center gap-3">
        {[1, 2, 3].map((s) => (
          <div
            key={s}
            className={`h-2.5 rounded-full transition-all duration-300 ${
              s === step ? 'w-8 bg-[#005448]' : s < step ? 'w-2.5 bg-[#2E7A5B]' : 'w-2.5 bg-stone-200 dark:bg-stone-700'
            }`}
          />
        ))}
      </div>

      {/* STEP 1: Voice-First Description */}
      {step === 1 && (
        <div className="space-y-3.5">
          <div className="bg-[#FAF9F4] dark:bg-[#13201E] p-3.5 rounded-2xl border border-[#E8E6DF] dark:border-stone-800 space-y-1">
            <h2 className="text-base font-black text-[#121E1C] dark:text-white">Tell us what you need in your own words</h2>
            <p className="text-xs text-stone-600 dark:text-stone-400">
              Speak or type. AI interprets the urgency & category automatically.
            </p>
          </div>

          <div className="relative">
            <textarea
              value={naturalText}
              onChange={(e) => setNaturalText(e.target.value)}
              placeholder="e.g. 'Need blood pressure medicines picked up from Jan Aushadhi pharmacy'..."
              rows={3}
              className="w-full rounded-2xl border-2 border-stone-200 dark:border-stone-700 bg-white dark:bg-[#14211F] p-3.5 pr-14 text-sm focus:border-[#005448] focus:outline-none transition-all resize-none shadow-xs text-stone-800 dark:text-stone-100 leading-normal"
            />

            <button
              type="button"
              onClick={handleVoiceToggle}
              aria-label={isListening ? 'Stop voice recording' : 'Start speech recognition'}
              className={`absolute right-3 bottom-3 p-2.5 rounded-xl transition-all shadow-md ${
                isListening
                  ? 'bg-red-500 text-white animate-pulse'
                  : 'bg-[#005448] text-white hover:bg-[#004239]'
              }`}
            >
              {isListening ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
            </button>
          </div>

          {/* Preset Quick Chips - Sleek Single Row */}
          <div className="space-y-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-stone-500 dark:text-stone-400">Quick Examples:</span>
            <div className="flex gap-1.5 overflow-x-auto pb-0.5 no-scrollbar">
              {[
                'Pick up prescription medicines from pharmacy',
                'Need ride to clinic tomorrow morning',
                'Need essential groceries delivered'
              ].map((chip, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => setNaturalText(chip)}
                  className="text-xs bg-stone-100 dark:bg-stone-800 hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-700 dark:text-stone-300 font-medium px-2.5 py-1 rounded-xl transition-colors whitespace-nowrap"
                >
                  "{chip}"
                </button>
              ))}
            </div>
          </div>

          <button
            type="button"
            disabled={!naturalText.trim() || isClassifying}
            onClick={handleProcessWithAI}
            className="w-full py-3.5 bg-[#005448] hover:bg-[#004239] disabled:opacity-50 text-white rounded-2xl font-bold text-sm uppercase tracking-wider flex items-center justify-center gap-2 shadow-md transition-all active:scale-98 cursor-pointer"
          >
            {isClassifying ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>AI Understanding Intent...</span>
              </>
            ) : (
              <span>Continue & Review Fields</span>
            )}
          </button>
        </div>
      )}

      {/* STEP 2: Review & Edit Structured Interpretation */}
      {step === 2 && (
        <div className="space-y-5">
          {isEmergencyDetected && (
            <div className="bg-red-600 text-white p-4 rounded-2xl space-y-2">
              <div className="flex items-center gap-2 font-black text-sm">
                <AlertTriangle className="w-5 h-5" />
                <span>Critical Medical Event Detected</span>
              </div>
              <p className="text-xs text-red-100">
                This request sounds like an acute medical emergency. Volunteer assistance is not an ambulance. Please trigger SOS immediately.
              </p>
              <button
                type="button"
                onClick={() => {
                  const sosBtn = document.querySelector('button[aria-label*="Emergency SOS"]') as HTMLButtonElement;
                  if (sosBtn) sosBtn.click();
                }}
                className="w-full bg-white text-red-600 font-black py-2 rounded-xl text-xs shadow-md mt-1"
              >
                Trigger SOS Rescue Now
              </button>
            </div>
          )}

          <div className="space-y-4 bg-white dark:bg-[#14211F] p-5 rounded-3xl border border-stone-200 dark:border-stone-800 shadow-sm">
            <div>
              <label className="text-xs font-bold text-stone-600 dark:text-stone-400 uppercase tracking-wider block mb-1">
                Request Title
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full border border-stone-300 dark:border-stone-700 rounded-xl p-3 text-sm font-semibold focus:border-[#005448] focus:outline-none bg-white dark:bg-stone-800/80 text-stone-900 dark:text-white"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-bold text-stone-600 dark:text-stone-400 uppercase tracking-wider block mb-1">
                  Category
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as any)}
                  className="w-full border border-stone-300 dark:border-stone-700 rounded-xl p-3 text-xs font-semibold focus:border-[#005448] focus:outline-none bg-white dark:bg-stone-800/80 text-stone-900 dark:text-white"
                >
                  <option value="medicine_pickup">Medicine Pickup</option>
                  <option value="transportation">Transportation</option>
                  <option value="grocery_pickup">Grocery Pickup</option>
                  <option value="health_check">Health Check</option>
                  <option value="companionship">Companionship</option>
                  <option value="custom">Other Custom Task</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-stone-600 dark:text-stone-400 uppercase tracking-wider block mb-1">
                  Urgency
                </label>
                <select
                  value={urgency}
                  onChange={(e) => setUrgency(e.target.value as any)}
                  className="w-full border border-stone-300 dark:border-stone-700 rounded-xl p-3 text-xs font-semibold focus:border-[#005448] focus:outline-none bg-white dark:bg-stone-800/80 text-stone-900 dark:text-white"
                >
                  <option value="critical">Critical / Immediate</option>
                  <option value="today">Today</option>
                  <option value="scheduled">Scheduled Later</option>
                </select>
              </div>
            </div>

            <div>
              <label className="text-xs font-bold text-stone-600 dark:text-stone-400 uppercase tracking-wider block mb-1">
                Task Details
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                className="w-full border border-stone-300 dark:border-stone-700 rounded-xl p-3 text-xs font-medium focus:border-[#005448] focus:outline-none bg-white dark:bg-stone-800/80 text-stone-900 dark:text-white"
              />
            </div>

            <div>
              <label className="text-xs font-bold text-stone-600 dark:text-stone-400 uppercase tracking-wider block mb-1">
                Your Pickup / Assistance Address
              </label>
              <input
                type="text"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                className="w-full border border-stone-300 dark:border-stone-700 rounded-xl p-3 text-sm font-semibold focus:border-[#005448] focus:outline-none bg-white dark:bg-stone-800/80 text-stone-900 dark:text-white"
              />
            </div>
          </div>

          <button
            type="button"
            onClick={() => setStep(3)}
            className="w-full py-4 bg-[#005448] hover:bg-[#004239] text-white rounded-2xl font-bold text-lg shadow-md transition-all active:scale-98"
          >
            Review & Broadcast
          </button>
        </div>
      )}

      {/* STEP 3: Final Confirmation & Safety Consent */}
      {step === 3 && (
        <div className="space-y-5">
          <div className="bg-white dark:bg-[#14211F] p-6 rounded-3xl border border-stone-200 dark:border-stone-800 shadow-sm space-y-4">
            <h3 className="text-xl font-black text-[#121E1C] dark:text-white">{title}</h3>

            <div className="space-y-2 text-xs text-stone-700 dark:text-stone-300">
              <p><strong>Category:</strong> {category.replace('_', ' ')}</p>
              <p><strong>Urgency:</strong> {urgency.toUpperCase()}</p>
              <p><strong>Location:</strong> {address}</p>
              <p><strong>Details:</strong> {description}</p>
            </div>

            <div className="p-4 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 rounded-2xl text-xs text-[#005448] dark:text-emerald-300 space-y-1">
              <span className="font-bold">Privacy & Trust Guarantee:</span>
              <p>
                Your exact home coordinates and health history remain private. Nearby verified community volunteers will only see the task description and general junction.
              </p>
            </div>
          </div>

          <button
            type="button"
            disabled={isCreating}
            onClick={handleFinalSubmit}
            className="w-full py-4 bg-[#2E7A5B] hover:bg-[#256349] disabled:opacity-50 text-white rounded-2xl font-black text-lg flex items-center justify-center gap-2 shadow-lg shadow-emerald-700/20 transition-all active:scale-98"
          >
            {isCreating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                <span>Broadcasting to Community...</span>
              </>
            ) : (
              <>
                <CheckCircle2 className="w-6 h-6" />
                <span>Submit Request to Neighbors</span>
              </>
            )}
          </button>
        </div>
      )}
    </div>
  );
};
